name: app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_slidable: ^1.2.0
  flutter_native_splash: ^2.3.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/src/app-icon.png"	
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter_native_splash:
  color: "#ffffff"
  image: assets/src/splash-icon.png
  color_dark: "#121212"

  android_12:
    image: assets/src/splash-icon.png
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/src/logo.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 500
  
